/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddWeightEntry: typeof import('./src/components/AddWeightEntry.vue')['default']
    Bmi: typeof import('./src/components/Bmi.vue')['default']
    CurrentWeight: typeof import('./src/components/CurrentWeight.vue')['default']
    MedianWeight: typeof import('./src/components/MedianWeightLost.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WeightEntriesChart: typeof import('./src/components/WeightEntriesChart.vue')['default']
    WeightEntryTable: typeof import('./src/components/WeightEntryTable.vue')['default']
    WeightLost: typeof import('./src/components/WeightLost.vue')['default']
  }
}
